import type { Listing } from './types';

/* ── Seller profiles for seed listings ── */
export interface SeedSeller {
  id: string;
  name: string;
  initial: string;
  rating: number;
  reviewCount: number;
  dept: string;
}

export const SEED_SELLERS: Record<string, SeedSeller> = {
  's1': { id: 's1', name: 'Arjun Menon',     initial: 'A', rating: 4.8, reviewCount: 23, dept: 'CSE • 3rd Year' },
  's2': { id: 's2', name: 'Priya Krishnan',  initial: 'P', rating: 4.6, reviewCount: 11, dept: 'ECE • 2nd Year' },
  's3': { id: 's3', name: 'Rahul Sharma',    initial: 'R', rating: 4.9, reviewCount: 34, dept: 'MECH • 4th Year' },
  's4': { id: 's4', name: 'Sneha Iyer',      initial: 'S', rating: 4.5, reviewCount: 8,  dept: 'IT • 3rd Year'  },
  's5': { id: 's5', name: 'Vikram Nair',     initial: 'V', rating: 4.7, reviewCount: 17, dept: 'EEE • 2nd Year' },
  's6': { id: 's6', name: 'Divya Ramesh',    initial: 'D', rating: 5.0, reviewCount: 6,  dept: 'BIOTECH • 3rd Year' },
  's7': { id: 's7', name: 'Karthik Subbu',   initial: 'K', rating: 4.3, reviewCount: 29, dept: 'CIVIL • 4th Year' },
};


export const SEED_LISTINGS: Listing[] = [
  /* ── TRENDING / BEST DEALS ── */
  {
    id: 'seed-01',
    sellerId: 's1',
    title: 'MacBook Air M1 (8GB / 256GB) — Near Mint',
    description:
      "Used for one semester of B.Tech. Zero scratches, battery health 97%. Comes with original charger and box. Upgrading to M3 so letting this go at a steal. Perfect for coding, design, or any engineering coursework. Pickup at Men's Hostel Block C.",
    category: 'electronics',
    condition: 'like-new',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1650661926447-9efb2610f64c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 42000,
    originalPrice: 72000,
    exchangePoint: "Men's Hostel Block C Gate",
    isUrgent: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-02',
    sellerId: 's2',
    title: 'Sony WH-1000XM4 Wireless Headphones',
    description:
      'Bought last year, used lightly. ANC works perfectly, 30hr battery still holds strong. Includes carry case and original cables. Great for long study sessions or coding in noisy common rooms. No repairs, no issues.',
    category: 'electronics',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 8500,
    originalPrice: 16000,
    exchangePoint: 'TT Square, Tech Tower',
    isUrgent: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-03',
    sellerId: 's3',
    title: 'B.Tech Sem 1–4 Complete Textbook Bundle (ECE)',
    description:
      'Full set: Engineering Maths (all 4 sem), EDC, Networks, Signals & Systems, BEEE, C Programming. All in good readable condition. Highlighted inside but all content intact. Selling as bundle only — huge savings vs buying each.',
    category: 'books',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 850,
    originalPrice: 2800,
    exchangePoint: 'Central Library Entrance',
    isUrgent: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-04',
    sellerId: 's4',
    title: 'Casio FX-991ES Plus Scientific Calculator',
    description:
      'Works perfectly. Used for 2 semesters of engineering maths and physics. No scratches on screen, all buttons functional. Casio FX-991ES Plus is allowed in all VIT exams. Comes with original cover.',
    category: 'stationery',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1648201637025-1c77b9be3013?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 550,
    originalPrice: 1150,
    exchangePoint: 'SJT Lobby Ground Floor',
    isUrgent: false,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-05',
    sellerId: 's5',
    title: 'Nike 32L Campus Backpack — Black',
    description:
      'Bought at the beginning of the year, switching to a sling. Fits 15" laptop, has padded back, multiple compartments. Very clean, no tears or fading. Perfect for daily campus use.',
    category: 'bags',
    condition: 'like-new',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1622560481156-01fc7e1693e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 1100,
    originalPrice: 2800,
    exchangePoint: "Anna Auditorium Gate",
    isUrgent: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-06',
    sellerId: 's6',
    title: 'Arduino Uno Starter Kit + Components',
    description:
      'Full starter kit with Uno R3, breadboard, jumper wires, resistors, LEDs, servo motor, LCD module, sensors (DHT11, IR, ultrasonic). Used for one mini project, everything still works. Great for IoT or mini-project season.',
    category: 'electronics',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1520467795206-62e33627e6ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 1600,
    originalPrice: 3400,
    exchangePoint: 'MB Ground Floor Canteen',
    isUrgent: false,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },

  /* ── URGENT SALES ── */
  {
    id: 'seed-07',
    sellerId: 's7',
    title: 'Atlas Cycle — Going Home, Must Sell TODAY',
    description:
      'Reliable campus cycle, used for 2 years. Tyres recently changed, brakes in good condition. Selling urgent — flight home is tomorrow morning. Price is flexible for quick pickup. Saves 20 min vs walking to Tech Tower!',
    category: 'other',
    condition: 'used',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1741676516502-69250deb38ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 2800,
    originalPrice: 6500,
    exchangePoint: "Men's Hostel Cycle Stand",
    isUrgent: true,
    urgentReason: 'Flying home tomorrow — must sell by tonight!',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-08',
    sellerId: 's1',
    title: 'Mini Fridge 45L — Hostel Approved Brand',
    description:
      'Godrej 45L mini fridge, hostel-approved model. Runs quietly, no issues. Moving to a day scholar stay so no point keeping it. Comes with shelves intact. First come first serve — hostel checkout is in 3 days.',
    category: 'hostel-essentials',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1540961403310-79825242906e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 3800,
    originalPrice: 7500,
    exchangePoint: "Women's Hostel Block A",
    isUrgent: true,
    urgentReason: 'Hostel checkout in 3 days — please DM fast.',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-09',
    sellerId: 's2',
    title: 'VIT Hoodie Size L — Selling Cheap, Last Day',
    description:
      'Official VIT Vellore hoodie, maroon, size L. Washed and clean. Selling today only — heading home for the holidays and bag is full. Price is final.',
    category: 'fashion',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 399,
    originalPrice: 950,
    exchangePoint: 'Hostel Junction Bus Stop',
    isUrgent: true,
    urgentReason: 'Selling today only. No holds.',
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },

  /* ── GIVE AWAY ── */
  {
    id: 'seed-10',
    sellerId: 's3',
    title: 'Data Structures & Algorithms — CLRS 3rd Ed.',
    description:
      'The big blue book! Introduction to Algorithms by CLRS (3rd edition). Slightly worn cover but all pages intact and readable. I have the PDF now, so free for whoever needs it. First message gets it.',
    category: 'books',
    condition: 'used',
    transactionType: 'give-away',
    photos: ['https://images.unsplash.com/photo-1525972385596-02ad3049150b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    exchangePoint: 'Takshashila Ground Floor',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-11',
    sellerId: 's4',
    title: 'Electric Kettle (1L) — Free, Just Collect',
    description:
      "Philips 1L kettle. Auto shut-off works, no rust, heats fast. I bought a new one so giving this away. Perfect for hostel tea/noodles. Pick up from Women's Hostel Block D anytime after 6 PM.",
    category: 'hostel-essentials',
    condition: 'good',
    transactionType: 'give-away',
    photos: ['https://images.unsplash.com/photo-1643114786355-ff9e52736eab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    exchangePoint: "Women's Hostel Block D",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-12',
    sellerId: 's5',
    title: 'Adjustable Desk Lamp — Free to Good Home',
    description:
      'White LED desk lamp with USB charging port on base. Brightness and colour temperature adjustable. One of the arms is slightly loose but holds position fine. Gives away because I prefer the ceiling light now.',
    category: 'hostel-essentials',
    condition: 'used',
    transactionType: 'give-away',
    photos: ['https://images.unsplash.com/photo-1519219788971-8d9797e0928e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    exchangePoint: 'Sapthagiri Hostel Lobby',
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },

  /* ── RENT NEARBY ── */
  {
    id: 'seed-13',
    sellerId: 's6',
    title: 'Canon EOS 1500D DSLR — Rent for Events',
    description:
      'Canon EOS 1500D with 18-55mm kit lens. Perfect for fests, Gravitas shoots, or personal projects. Comes with 32GB SD card and extra battery. I will need a ₹2000 refundable deposit. Available weekends and during fest season.',
    category: 'electronics',
    condition: 'like-new',
    transactionType: 'rent',
    photos: ['https://images.unsplash.com/photo-1616400619175-5beda3a17896?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    rentalRateDay: 300,
    rentalRateWeek: 1500,
    rentalDeposit: 2000,
    rentalNotes: 'Deposit refunded on return. No physical damage allowed.',
    exchangePoint: 'GDN Block Ground Floor',
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-14',
    sellerId: 's7',
    title: 'Lenovo IdeaPad Laptop — Rent Per Day / Week',
    description:
      'Lenovo IdeaPad 5, Intel i5 11th Gen, 8GB RAM, 512GB SSD. Windows 11 clean install. Ideal if your laptop is in repair or you need a backup during exams. VS Code, Python, Java, all dev tools pre-installed.',
    category: 'electronics',
    condition: 'good',
    transactionType: 'rent',
    photos: ['https://images.unsplash.com/photo-1650661926447-9efb2610f64c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    rentalRateDay: 200,
    rentalRateWeek: 950,
    rentalDeposit: 3000,
    rentalNotes: 'Treat it like your own. Deposit refundable.',
    exchangePoint: 'Tech Tower Food Court',
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-15',
    sellerId: 's1',
    title: 'Bicycle Rent — ₹80/Day, ₹400/Week',
    description:
      'BSA cycle in good running condition. Ideal for getting between hostels and academic blocks without walking in the heat. Available daily, collect and return at hostel gate. Helmet available on request.',
    category: 'other',
    condition: 'good',
    transactionType: 'rent',
    photos: ['https://images.unsplash.com/photo-1741676516769-6f33bec11efd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    rentalRateDay: 80,
    rentalRateWeek: 400,
    rentalDeposit: 500,
    rentalNotes: 'Return by 9PM. Lock provided.',
    exchangePoint: "Men's Hostel Cycle Stand",
    createdAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
  },

  /* ── RECENTLY LISTED / MISC ── */
  {
    id: 'seed-16',
    sellerId: 's2',
    title: 'Clean Code + Design Patterns Bundle',
    description:
      "Two classic software engineering reads: 'Clean Code' by Robert C. Martin and 'Head First Design Patterns'. Both in very good condition. Perfect for placement prep or senior project season.",
    category: 'books',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1520467795206-62e33627e6ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 600,
    originalPrice: 1800,
    exchangePoint: 'Viswam Library Reading Hall',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-17',
    sellerId: 's3',
    title: "JBL Flip 5 Bluetooth Speaker — Waterproof",
    description:
      'JBL Flip 5 in Teal. Excellent condition, bought 8 months ago. Battery lasts ~10 hrs on a charge. Waterproof so great for bathroom, outdoor jam sessions on campus lawns. No scratches.',
    category: 'electronics',
    condition: 'like-new',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 2800,
    originalPrice: 5500,
    exchangePoint: 'Cafeteria A Block',
    isUrgent: false,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-18',
    sellerId: 's4',
    title: 'Ergonomic Study Chair — Back-Support',
    description:
      'Foldable mesh-back ergonomic chair. Height adjustable, lumbar support, armrests. Used for one year but spine is in great shape. Useful if you spend 6+ hrs studying at your desk. Slightly dusty but wipes clean easily.',
    category: 'furniture',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1519219788971-8d9797e0928e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 1400,
    originalPrice: 3200,
    exchangePoint: 'Hostel E Block Room 214',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-19',
    sellerId: 's5',
    title: 'Exchange: Python Textbook for DSA Book',
    description:
      "I have 'Automate the Boring Stuff with Python' (hardcover) and looking for any good DSA book — Narasimha Karumanchi or similar. DM if interested in swapping!",
    category: 'books',
    condition: 'good',
    transactionType: 'exchange',
    photos: ['https://images.unsplash.com/photo-1525972385596-02ad3049150b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    exchangePreference: 'DSA / Data Structures book — any edition',
    exchangePoint: 'SJT 4th Floor Corridor',
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: 'seed-20',
    sellerId: 's6',
    title: 'Quechua 50L Hiking Backpack',
    description:
      "Decathlon Quechua 50L backpack in olive green. Used for one Coorg trip. All zips work, padded straps, rain cover included. Great for weekend treks with VIT adventure clubs or travel back home.",
    category: 'bags',
    condition: 'good',
    transactionType: 'sell',
    photos: ['https://images.unsplash.com/photo-1581605405669-fcdf81165afa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800'],
    status: 'available',
    price: 1800,
    originalPrice: 3999,
    exchangePoint: 'Ganga Hostel Gate',
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
];
